Angular todo dv
ForgeRock/sdk-sample-apps pull request #18
Opened 2024-11-13 22:24 UTC by ericanderson91

Angular Sample for davinci client 

https://pingidentity.atlassian.net/browse/SDKS-3195

2024-11-19 17:01 UTC, cerebrl requested changes
Just a cursory review of the PR. Left a few comments that will require some refactoring. Please reach out if you have any questions.

2024-11-19 17:01 UTC, cerebrl commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
These collector components don't seem to have any error handling on them at all. When we get a node type of `error`, we should grab the cached response from the endpoint and pull the input level error message from it to indicate the error for correction. Right now, I think we're just treating all non-successes as failures, which require restarting the flow entierly.

2024-11-19 18:04 UTC, ericanderson91 commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
I noticed this as well, I ASSumed it was a current limitation of the SDK or something. So we do display a general form error but then we hide all the collector fields when an error is encountered.

So I may be doing something wrong but in order to get the error message I need to call `this.davinciClient.next()` and at that point the collectors start throwing not found errors and I can't update the values and attempt to resubmit the node.

![image](https://github.com/user-attachments/assets/d8827e9d-c66b-41b2-b86b-c1b3b08b7b25)

2024-11-21 16:37 UTC, cerebrl commented on angular-todo-dv/src/app/features/davinci-client/davinci-flow/davinci-flow.component.ts
> +  }
Thanks for explaining the intent behind your implementation. I have to admit I am _not_ an Angular expert, so take what I say with a grain of salt. 

I tried to find more information on passing functions to child components, but I honestly couldn't find good information on it. It seems there are many ways to pass functions and methods to components. I do see that the major complaint is the binding of the `this` keyword when sharing a method of the parent class with the child component.

I guess I can imagine the issue with this is the iteration of collectors is done within the template, and not within the JavaScript context like React. So, is there no way to call `davinciClient.update(collector)` during iteration time, passing the returned value (a function) to the component. Is that the issue?

Just to be clear, the function that is returned from the `davinciClient.update(collector)`, is solely for the collector component. The parent component has no need for it at all. So, this isn't parent-child communication per se, but literally just creating an isolated function during iteration for each collector's own use. The collector component calls that update function and the internal store of the DaVinci Client updates the value of that collector.

Anyway, if you still feel strongly about the pattern used, I'm okay with it as you likely have more experience with Angular than I do. I appreciate your patience with me :)

2024-11-21 16:53 UTC, cerebrl commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
No, you are not doing anything wrong per se; it's just not very obvious how to handle this. So, what you have to do is call `next` and receive the new node, but you need to hold on to the previous node, which contains the collectors. If the new node is an error (not failure), you need to reuse the old node and render both the error message along with the old node containing its collectors.

After correcting the error, you should be able to submit the previous node with the new values. I hope that makes sense.

2024-11-21 17:04 UTC, ericanderson91 commented on angular-todo-dv/src/app/features/davinci-client/davinci-flow/davinci-flow.component.ts
> +  }
Yeah with Angular your templates and javascript are completely separate so you can't always use the same patterns as with React. They (angular team) have strong opinions about how to do stuff which I don't always agree with, there's a reason I made a career swift away from Angular :).

I made a slight refactor which moves creating those update functions into the iteration loop, I'm okay with that. I am going to stand my ground on not making the form fields dependent on the SDK though.

https://github.com/ForgeRock/sdk-sample-apps/pull/18/commits/051f5d8cb22820e68038ba9f89456a4f462dd536

2024-11-21 19:42 UTC, cerebrl commented on angular-todo-dv/src/app/features/davinci-client/davinci-flow/davinci-flow.component.ts
> +  }
Sure, this seems like a good compromise. No need to stand your ground, though. We trust your opinion :)

2024-11-21 20:05 UTC, ericanderson91 commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
Thanks for the clarification, that makes sense, just have other priorities at the moment, I'll get that updated later today or tomorrow and let you know!

2024-11-21 20:19 UTC, cerebrl commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
Thanks! Take your time; we're just happy that you're able to help :)

2025-02-27 21:21 UTC, ericanderson91 commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
I attempted to revisit this today. First of all I tried to update the davinci-client to v1.0.0 and it is throwing a typescript error.

![Screenshot 2025-02-27 at 2 04 04 PM](https://github.com/user-attachments/assets/90ca6dc3-cad3-47d9-80c1-a8ee8eaefc41)

I was able to workaround this by manually changing that reference in `node_modules/@forgerock/davinci-client/dist/lib/config.types.d.ts` from `@forgerock/javascript-sdk/src/config/interfaces` to `@forgerock/javascript-sdk/dist/config/interfaces`, but looks like you may need to updated something with your typings output or something. Once I did that everything built just fine. 

But I am unable to submit with the `next` function after I encounter an error. Note in the screenshot I am displaying the error and the form fields, and in the console you can see that the update function is being called but there are errors when I try to use the collector to update the values. Then the SDK seems to be doing a postback instead of trying to submit the data to the endpoint.

![Screenshot 2025-02-27 at 2 18 15 PM](https://github.com/user-attachments/assets/548b5a44-11a2-41a0-a6e0-c4bfcc20f690)

2025-02-28 00:03 UTC, ryanbas21 commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
> I attempted to revisit this today. First of all I tried to update the davinci-client to v1.0.0 and it is throwing a typescript error.
> 
> ![Screenshot 2025-02-27 at 2 04 04 PM](https://private-user-images.githubusercontent.com/95306299/417785149-90ca6dc3-cad3-47d9-80c1-a8ee8eaefc41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA3MDA5NTYsIm5iZiI6MTc0MDcwMDY1NiwicGF0aCI6Ii85NTMwNjI5OS80MTc3ODUxNDktOTBjYTZkYzMtY2FkMy00N2Q5LTgwYzEtYThlZThlYWVmYzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI3VDIzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NGY1Mjk1YTJmMDY5ZmNiMGRhYzFjZDU1OWUxNWMwZmU1MDQ0MzVhY2ZiMTdkYzAxZTNjNmZjZGYxN2VhNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BoLGV1kfc4WSYxiiNAsDnuspyr2x1QhsUBuwCXwRdTs)
> 
> I was able to workaround this by manually changing that reference in `node_modules/@forgerock/davinci-client/dist/lib/config.types.d.ts` from `@forgerock/javascript-sdk/src/config/interfaces` to `@forgerock/javascript-sdk/dist/config/interfaces`, but looks like you may need to updated something with your typings output or something. Once I did that everything built just fine.
> 
> But I am unable to submit with the `next` function after I encounter an error. Note in the screenshot I am displaying the error and the form fields, and in the console you can see that the update function is being called but there are errors when I try to use the collector to update the values. Then the SDK seems to be doing a postback instead of trying to submit the data to the endpoint.
> 
> ![Screenshot 2025-02-27 at 2 18 15 PM](https://private-user-images.githubusercontent.com/95306299/417788204-548b5a44-11a2-41a0-a6e0-c4bfcc20f690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA3MDA5NTYsIm5iZiI6MTc0MDcwMDY1NiwicGF0aCI6Ii85NTMwNjI5OS80MTc3ODgyMDQtNTQ4YjVhNDQtMTFhMi00MWEwLWE2ZTAtYzRiZmNjMjBmNjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI3VDIzNTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODgzNjk0M2JiNTEyMWNmOWNlNmZmNThmMmFiYTAyN2UwOWExMDc4NmUyZDFiOGYyZGEzZjMyMjQ4NGZiMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hp43PHqX_qoQR4WhCetG1ALTghvPQR-FwJ0IFT3P0Q8)

I checkout out the last commit from this branch and I was able to build without any changes. However, the type error your getting is most likely because of the ts configuration.

I would gander that the tsconfig.json (or tsconfig.app.json) needs to be `moduleResolution: Bundler`

This is partially the SDKS fault, but in this scenario, this would be the correct module setting for the angular app because it is the host application, which is using a bundler which would be responsible for the module resolution / linking.

2025-02-28 00:06 UTC, ryanbas21 commented on angular-todo-dv/src/app/features/davinci-client/password/password.component.html
In regards to the latter problem, do you have a har file that can show this or can you put here a simple few reproduction steps so I can try to replicate this?

2025-05-06 20:17 UTC, closed without merging