Add swiftui-davinci sample app
ForgeRock/sdk-sample-apps pull request #22
Opened 2024-11-26 00:50 UTC by vahancouver

[SDKS-3415](https://pingidentity.atlassian.net/browse/SDKS-3415)
[iOS] [Unified] [DV] - Move DaVinci Sample App into Sample App Repo

2024-11-26 19:57 UTC, rodrigoareis requested changes
Overall changes looks good! Left some comments to address

2024-11-26 19:57 UTC, rodrigoareis commented on iOS/README.md
> +-  [**Davinci using SwiftUI - `/ios/swiftui-davinci`**](./swiftui-davinci/)
Add a README file to the sample app folder. You can follow the structure of the `kotlin-davinci`

2024-11-26 19:57 UTC, rodrigoareis commented on iOS/swiftui-davinci/Davinci/Davinci/AccessToken.swift
> +struct AccessTokenView: View {
Generate docs for the code

2024-11-26 21:32 UTC, rodrigoareis commented on iOS/swiftui-davinci/Davinci/Davinci.xcodeproj/project.pbxproj
> +		3AE945732BF27223007B3381 /* LoginUtility.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = LoginUtility.swift; sourceTree = "<group>"; };
Remove reference, file was removed

2024-11-26 22:42 UTC, rodrigoareis commented on iOS/swiftui-davinci/Davinci/Davinci/ContentView.swift
> +          DavinciView(path: $path)
`DavinciView` is missing. Some others in this switch statement were removed intentionally, so should be removed here.

2024-11-27 22:46 UTC, rodrigoareis approved these changes
Changes looks good to me

2024-11-28 04:25 UTC, spetrov approved these changes
LGTM! 👍🏻

2024-11-28 04:29 UTC, merged